# Generated by Django 4.0 on 2022-06-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=50)),
                ('title', models.CharField(default='', max_length=256)),
                ('image', models.URLField(max_length=256)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('desc', models.TextField()),
                ('tag', models.ManyToManyField(related_name='movies', to='movie.Tag')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.ManyToManyField(to='movie.Movie')),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
